language: rust
rust:
  - stable

install:
  - sudo apt-get install python-unittest2
  - sudo pip install ghp-import urllib3[secure] autobahntestsuite

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"

stages:
    - build
    - test

jobs:
    include:
        - stage: "Build"
          script: cargo build --release
        - stage: "Test"
          script: cargo test --release
        - script: ./scripts/autobahn-client.sh
        - script: ./scripts/autobahn-server.sh
